title: Cem Alpaslan
logo: /github.png.jpg

description: |
  Operations Research | Optimisation

  📍 Perth, Western Australia

  [![LinkedIn](https://img.shields.io/badge/LinkedIn-Connect-blue?logo=linkedin)](https://linkedin.com/in/cem-alpaslan-34921a184)
  [![GitHub](https://img.shields.io/badge/GitHub-Follow-black?logo=github)](https://github.com/CemAlpaslan23)

  [![Curtin Email](https://img.shields.io/badge/Email-Curtin-red?logo=gmail)](mailto:cem.alpaslan@student.curtin.edu.au)
  [![Sabancı Alumni](https://img.shields.io/badge/Email-Sabanci-orange?logo=gmail)](mailto:cemalpaslan@alumni.sabanciuniv.edu)

theme: jekyll-theme-minimal

