title: Cem Alpaslan
logo: /Github.jpg

description: |
  Operations Research Graduate Portfolio<br>
  📍 Perth, Western Australia<br>
  📞 +61 434 235 460<br>
  📧 cem.alpaslan@student.curtin.edu.au<br>
  💼 linkedin.com/in/cem-alpaslan-34921a184

theme: jekyll-theme-minimal
